#if !defined(__SWL_PATTERN_RECOGNITION__EXPORT_PATTERN_RECOGNITION__H_)
#define __SWL_PATTERN_RECOGNITION__EXPORT_PATTERN_RECOGNITION__H_ 1


#if defined(WIN32) || defined(_WIN32)
#	if defined(_MSC_VER)
#		if defined(SWL_PATTERN_RECOGNITION_EXPORT)
#		    define SWL_PATTERN_RECOGNITION_API __declspec(dllexport)
#			define SWL_PATTERN_RECOGNITION_TEMPLATE_EXTERN
#		else
#		    define SWL_PATTERN_RECOGNITION_API __declspec(dllimport)
#			define SWL_PATTERN_RECOGNITION_TEMPLATE_EXTERN extern
#		endif  // SWL_PATTERN_RECOGNITION_EXPORT
#	else
#		define SWL_PATTERN_RECOGNITION_API
#		define SWL_PATTERN_RECOGNITION_TEMPLATE_EXTERN
#	endif  // _MSC_VER
#elif defined(__MINGW32__)
#	if defined(_USRDLL)
#		if defined(SWL_PATTERN_RECOGNITION_EXPORT)
#			define SWL_PATTERN_RECOGNITION_API __declspec(dllexport)
#		else
#			define SWL_PATTERN_RECOGNITION_API __declspec(dllimport)
#		endif  // SWL_PATTERN_RECOGNITION_EXPORT
#	else
#		define SWL_PATTERN_RECOGNITION_API
#	endif  // _USRDLL
#	define SWL_PATTERN_RECOGNITION_TEMPLATE_EXTERN
#else
#   define SWL_PATTERN_RECOGNITION_API
#	define SWL_PATTERN_RECOGNITION_TEMPLATE_EXTERN
#endif


#endif  // __SWL_PATTERN_RECOGNITION__EXPORT_PATTERN_RECOGNITION__H_
