#if !defined(__SWL_GESTURE_RECOGNITION__EXPORT_GESTURE_RECOGNITION__H_)
#define __SWL_GESTURE_RECOGNITION__EXPORT_GESTURE_RECOGNITION__H_ 1


#if defined(WIN32)
#	if defined(_MSC_VER)
#		if defined(EXPORT_SWL_GESTURE_RECOGNITION)
#		    define SWL_GESTURE_RECOGNITION_API __declspec(dllexport)
#			define SWL_GESTURE_RECOGNITION_EXPORT_TEMPLATE
#		else
#		    define SWL_GESTURE_RECOGNITION_API __declspec(dllimport)
#			define SWL_GESTURE_RECOGNITION_EXPORT_TEMPLATE extern
#		endif  // EXPORT_SWL_GESTURE_RECOGNITION
#	else
#		define SWL_GESTURE_RECOGNITION_API
#		define SWL_GESTURE_RECOGNITION_EXPORT_TEMPLATE
#	endif  // _MSC_VER
#elif defined(__MINGW32__)
#	if defined(_USRDLL)
#		if defined(EXPORT_SWL_GESTURE_RECOGNITION)
#			define SWL_GESTURE_RECOGNITION_API __declspec(dllexport)
#		else
#			define SWL_GESTURE_RECOGNITION_API __declspec(dllimport)
#		endif  // EXPORT_SWL_GESTURE_RECOGNITION
#	else
#		define SWL_GESTURE_RECOGNITION_API
#	endif  // _USRDLL
#	define SWL_GESTURE_RECOGNITION_EXPORT_TEMPLATE
#else
#   define SWL_GESTURE_RECOGNITION_API
#	define SWL_GESTURE_RECOGNITION_EXPORT_TEMPLATE
#endif


#endif  // __SWL_GESTURE_RECOGNITION__EXPORT_GESTURE_RECOGNITION__H_
