//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WglViewTest.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_WglViewTestTYPE             129
#define IDR_TOOLBAR1                    130
#define IDR_WglSceneGraphViewTYPE       130
#define IDB_BITMAP1                     132
#define IDR_TOOLBAR2                    133
#define IDB_BITMAP2                     134
#define ID_PRINTANDCAPTURE_PRINTVIEWUSINGGDI 32779
#define ID_PRINTANDCAPTURE_CAPTUREVIEWUSINGGDI 32780
#define ID_PRINTANDCAPTURE_CAPTUREVIEWUSINGGDIPLUS 32781
#define ID_PRINTANDCAPTURE_COPYTOCLIPBOARD 32782
#define ID_VIEWHANDLING_PAN             32783
#define ID_VIEWHANDLING_ROTATE          32784
#define ID_VIEWHANDLING_ZOOMREGION      32785
#define ID_VIEWHANDLING_ZOOMALL         32786
#define ID_VIEWHANDLING_ZOOMIN          32787
#define ID_VIEWHANDLING_ZOOMOUT         32788
#define ID_VIEWHANDLING_PICKOBJECT      32789
#define ID_VIEWHANDLING_TOPVIEW         32803
#define ID_VIEWHANDLING_BOTTOMVIEW      32804
#define ID_VIEWHANDLING_FRONTVIEW       32805
#define ID_VIEWHANDLING_REARVIEW        32806
#define ID_VIEWHANDLING_LEFTVIEW        32807
#define ID_VIEWHANDLING_RIGHTVIEW       32808
#define ID_VIEWHANDLING_SHOWPERSPECTIVE 32809
#define ID_VIEWHANDLING_SHOWWIREFRAME   32810
#define ID_VIEWHANDLING_SHOWBACKGROUND  32811
#define ID_VIEWHANDLING_SHOWFLOOR       32812
#define ID_VIEWHANDLING_SHOWCOORDINATEFRAME 32813
#define ID_VIEWHANDLING_SHOWCOLORBAR    32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
