# Makefile for C++.

include ../../Makefile_common.cyg

#----------------------------------------------------------------------------

ifeq ($(BUILD_MODE),_DEBUG)
	OUT_DIR=./Debug_Cygwin
	INSTALL_DIR=../../Lib/Debug_Cygwin
else
ifeq ($(BUILD_MODE),_DEBUG_PROFILE)
	OUT_DIR=./Profile_Cygwin
	INSTALL_DIR=../../Lib/Profile_Cygwin
else
	OUT_DIR=./Release_Cygwin
	INSTALL_DIR=../../Lib/Release_Cygwin
endif
endif

SRCS=main.cpp
OBJS_BASE=$(SRCS:.cpp=.o)
OBJS=$(addprefix $(OUT_DIR)/, $(OBJS_BASE))

ifeq ($(LIB_BUILD_TYPE),__BUILD_SHARED_LIB)
	TARGET=base_test.exe
else
	TARGET=base_test.exe
endif

#----------------------------------------------------------------------------

INCS=-I/usr/include/g++-3 -I../../Include
LIB_SEARCH_PATH=-L./ -L/lib/ -L/usr/lib/ -L../../Lib/Release_Cygwin/
ifeq ($(LIB_BUILD_TYPE),__BUILD_SHARED_LIB)
	LIBS=$(LIB_SEARCH_PATH) -lswl_base -lstdc++
else
	LIBS=$(LIB_SEARCH_PATH) -lswl_base_static -lstdc++
endif

BASIC_DEF=
#AUXILIARY_DEF=-mno-cygwin -mwindows -mconsole
AUXILIARY_DEF=-mconsole

#DEP_INCS=-I/usr/include/g++-3 -I../../Include
#DEP_FLAGS=-M -MG -nostdinc -nostdinc++
DEP_INCS=$(INCS)
DEP_FLAGS=$(DEP_INCS) -MM -MG

STRIP=strip

#----------------------------------------------------------------------------

all : $(OUT_DIR)/$(TARGET) install

$(OUT_DIR)/$(TARGET) : $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)
	$(STRIP) $@

install :
	$(CP) $(OUT_DIR)/$(TARGET) $(INSTALL_DIR)/

uninstall :
	$(RM) $(INSTALL_DIR)/$(TARGET)

clean :
#	$(RM) $(OBJS) core
	$(RM) $(OUT_DIR)/*.o $(OUT_DIR)/$(TARGET)

new :
#	touch $(SRCS); %(MAKE)
	$(MAKE) clean
	$(MAKE)

dep :
#	gccmakedep $(DEP_INCS) $(SRCS)
	$(CXX) $(DEP_FLAGS) $(BASIC_DEF) $(AUXILIARY_DEF) $(SRCS) > Makefile.depend

#.cpp.o :
$(OUT_DIR)/%.o : %.cpp
	$(CXX) $(CXXFLAGS) $(BASIC_DEF) $(AUXILIARY_DEF) $(OUTPUT_OPTION) -c $<

#----------------------------------------------------------------------------
# Dependency.

include Makefile.depend
