//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinViewTest.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_WinViewTestTYPE             129
#define IDR_TOOLBAR1                    130
#define ID_PRINTANDCAPTURE_PRINTVIEWUSINGGDI 32785
#define ID_PRINTANDCAPTURE_CAPTUREVIEWUSINGGDI 32786
#define ID_PRINTANDCAPTURE_CAPTUREVIEWUSINGGDIPLUS 32787
#define ID_PRINTANDCAPTURE_COPYTOCLIPBOARD 32788
#define ID_VIEWHANDLING_PAN             32789
#define ID_VIEWHANDLING_ROTATE          32790
#define ID_VIEWHANDLING_ZOOMREGION      32791
#define ID_VIEWHANDLING_ZOOMALL         32792
#define ID_VIEWHANDLING_ZOOMIN          32793
#define ID_VIEWHANDLING_ZOOMOUT         32794
#define ID_VIEWHANDLING_PICKOBJECT      32795
#define ID_BUTTON32800                  32800
#define ID_VIEWHANDLING_SHOWBACKGROUND  32807
#define ID_VIEWHANDLING_SHOWFLOOR       32808
#define ID_VIEWHANDLING_SHOWCOORDINATEFRAME 32809
#define ID_VIEWHANDLING_SHOWCOLORBAR    32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
