#if !defined(__SWL_WIN_VIEW__GDI_PRINT_CONTEXT__H_ )
#define __SWL_WIN_VIEW__GDI_PRINT_CONTEXT__H_ 1


#include "swl/winview/GdiContextBase.h"


namespace swl {

//-----------------------------------------------------------------------------------
//  Print Context for GDI in Microsoft Windows

class SWL_WIN_VIEW_API GdiPrintContext: public GdiContextBase
{
public:
	typedef GdiContextBase base_type;

public:
	GdiPrintContext(HDC printDC, const Region2<int>& drawRegion, const bool isAutomaticallyActivated = true);
	GdiPrintContext(HDC printDC, const RECT& drawRect, const bool isAutomaticallyActivated = true);
	virtual ~GdiPrintContext();

private:
	GdiPrintContext(const GdiPrintContext &);
	GdiPrintContext & operator=(const GdiPrintContext &);

public:
	/// swap buffers
	/*virtual*/ bool swapBuffer();
	/// resize the context
	/*virtual*/ bool resize(const int x1, const int y1, const int x2, const int y2);

	/// get the native context
	/*virtual*/ boost::any getNativeContext()  {  return isActivated() ? boost::any(&memDC_) : boost::any();  }
	/*virtual*/ const boost::any getNativeContext() const  {  return isActivated() ? boost::any(&memDC_) : boost::any();  }

private:
	/// activate the context
	/*virtual*/ bool activate();
	/// de-activate the context
	/*virtual*/ bool deactivate();

	bool createOffScreen();
	bool createOffScreenBitmap(const int colorBitCount, const int colorPlaneCount);
	void deleteOffScreen();
	
private:
	/// a target print context
	HDC printDC_;

	/// a buffered context
	HDC memDC_;
	/// a buffered bitmap
	HBITMAP memBmp_;
	/// a old bitmap
	HBITMAP oldBmp_;
    /// an off-screen surface generated by the DIB section
	void *dibBits_;
};

}  // namespace swl


#endif  // __SWL_WIN_VIEW__GDI_PRINT_CONTEXT__H_
